apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ic-deploy-nautilus
  name: ic-deploy-nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-nautilus
  strategy: {}
  template:
    metadata:
      labels:
        app: ic-nautilus
    spec:
      volumes:
        - name: ic-volume-nautilus
          emptyDir: {}
      initContainers:
        - name: ic-msg-nautilus
          image: fedora:latest
          command:
            [
              "/bin/bash",
              "-c",
              "echo Init Done - Welcome to xFusionCorp Industries > /ic/official"
            ]
          volumeMounts:
            - mountPath: /ic
              name: ic-volume-nautilus
      containers:
      - image: fedora:latest
        name: ic-main-nautilus
        command:
          [
            "/bin/bash",
            "-c",
            "while true; do cat /ic/official; sleep 5; done"
          ]
        volumeMounts:
          - mountPath: /ic
            name: ic-volume-nautilus
        resources: {}
status: {}
