apiVersion: apps/v1 
kind: Persistentvolume # Letter case is wrong, should be PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard       
  capacity:
    storage: 250Mi
  accessModes: ReadWriteOnce # Should be a list
  hostPath:                       
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: 
    - Retain   # Should NOT be a list
---    
apiVersion: apps/v1 
kind: Persistentvolumeclaim  # Letter case is wrong, should be PersistentVolumeClaim
metadata:                          
  name: mysql-pv-claim
  labels:
    app: mysql-app 
spec:                              
  storageClassName: standard       
  accessModes: ReadWriteOnce  # Should be a list
  resources:
    requests:
      storage: 250MB 
---
apiVersion: v1                    
kind: Service                      
metadata:
  name: mysql         
  labels:             
  app: mysql-app # Should be nested under `labels`
spec:
  type: NodePort
  ports:
    - targetPort: 3306
      port: 3306
      nodePort: 30011
  selector:                       
    app: mysql_app
    tier: mysql
---
apiVersion: app/v1 
kind: Deployment                    
metadata:
  name: mysql-deployment           
  labels:                         
    app: mysql-app # Should be nested under `labels`
spec:
  selector:
    matchlabels: # Should be matchLabels
      app: mysql-app 
      tier: mysql 
  strategy:
    type: Recreate 
  template:         
    metadata:
      labels:        
        app: mysql-app
        tier: mysql
    spec:            
      containers:
      - image: mysql:5.6 
        name: mysql
        env:              
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:     
            secretKeyRef:
            name: mysql-root-pass # Indentation wrong
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
            name: mysql-db-url # Indentation wrong
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
            name: mysql-user-pass # Indentation wrong
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
            name: mysql-user-pass # Indentation wrong
              key: password
        ports:
        - containerPort: 3306              
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:                        
      - name: mysql-persistent-storage
          persistentVolumeClaim: # Indentation wrong
          claimName: mysql-pv-claim