apiVersion: v1
kind: Service # Important!
metadata:
  name: httpd-service-xfusion
  namespace: httpd-namespace-xfusion
spec:
  type: NodePort
  selector:
    app: httpd_app
  ports:
    - port: 80
      targetPort: 80 # Port where requests land up!
      nodePort: 30004 # Port where service is accessed.
