apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
  labels:
    name: myapp
spec:
  volumes:
    - name: secret-volume-nautilus
      secret:
        secretName: official # Important! must match secret
  containers:
    - name: secret-container-nautilus
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: secret-volume-nautilus
          mountPath: /opt/apps # Secret file will be placed here
          readOnly: true