apiVersion: v1
kind: Service # Important!
metadata:
  name: nginx-phpfpm
spec:
  type: NodePort
  selector:
    app: nginx-phpfpm # This is important - used by Pod.yaml spec.
  ports:
    - port: 8092
      targetPort: 8092 # Port where requests land up!
      nodePort: 30012 # Port where service is accessed.