apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: drupal-mysql-pv # Make sure matches with requirement
  labels:
    type: local
spec:
  storageClassName: standard       
  capacity:
    storage: 5Gi # Important
  accessModes:
    - ReadWriteOnce 
  hostPath:                       
    path: "/drupal-mysql-data"
  persistentVolumeReclaimPolicy: Retain
---    
apiVersion: v1 
kind: PersistentVolumeClaim # Important, the type of object
metadata:                          
  name: drupal-mysql-pvc # Again, must match with spec
  labels:
    app: mysql-app 
spec:                              
  storageClassName: standard       
  accessModes:
    - ReadWriteOnce             
  resources:
    requests:
      storage: 3Gi # Spec!
---
apiVersion: v1                    
kind: Service                      
metadata:
  name: drupal-mysql-service         
  labels:             
    app: mysql-app  
spec:
  type: NodePort
  ports:
    - targetPort: 3306
      port: 3306
      nodePort: 30096
  selector:                       
    app: mysql-app
    tier: mysql
---
apiVersion: apps/v1 
kind: Deployment                    
metadata:
  name: drupal-mysql           
  labels:                         
    app: mysql-app   
spec:
  replicas: 1
  selector:
    matchLabels:                  
      app: mysql-app 
      tier: mysql 
  strategy:
    type: Recreate 
  template:         
    metadata:
      labels:        
        app: mysql-app
        tier: mysql
    spec:            
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-db-url 
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass 
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass 
              key: password
        ports:
        - containerPort: 3306              
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  
          mountPath: /var/lib/mysql
      volumes:                        
      - name: mysql-persistent-storage
        persistentVolumeClaim: 
          claimName: drupal-mysql-pvc