apiVersion: v1                    
kind: Service                      
metadata:
  name: drupal-mysql-service         
  labels:             
    app: mysql-app  
spec:
  type: NodePort
  ports:
    - targetPort: 3306
      port: 3306
      nodePort: 30096
  selector:                       
    app: mysql-app
    tier: mysql