apiVersion: v1 
kind: Service 
metadata: 
  name: web-xfusion
spec: 
   type: NodePort 
   selector: 
     app: pv-nginx
   ports: 
     - port: 80 
       targetPort: 80 
       nodePort: 30008 # Expose the web server